# docs_task:
#   skip: $CIRRUS_BRANCH =~ '.*\.tmp'
#   container:
#     image: python:3.8-slim

#   install_script:
#     - apt update && apt install make
#     - pip install --upgrade-strategy eager -U -r requirements-docs.txt
#     - pip install -e .

#   script:
#     - make -C docs/ html

lint_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  container:
    image: python:3-slim

  install_script:
    - pip install poetry
    - poetry install
  script:
    - flake8

pep517_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  container:
    image: python:3-slim

  install_script:
    - pip install pep517

  script:
    - python3 -m pep517.check .

test_task:
  skip: $CIRRUS_BRANCH =~ '.*\.tmp'
  container:
    image: python:3-slim

  install_script:
    - pip install poetry
    - poetry install
  script:
    - pytest
